#####################################################

[proxy]
# Default values are based on the default servers
# generated when creating new velocity network.

ignored = []
linked = ["lobby", "factions", "minigames"]

#####################################################

[sql]
host = "localhost"
port = 3306
username = "root"
password = ""
database = "relink"

#####################################################