#####################################################

[proxy]
# Default values are based on the default servers
# generated when creating new velocity network.
linked = ["lobby", "factions", "minigames"]

#####################################################

[sql]
url = ""
username = ""
password = ""

#####################################################